repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: autopep8-wrapper
      args:
        - --in-place
        - --max-line-length=99
        - --ignore=E402,W503
    - id: flake8
      args:
        - --max-line-length=99
        - --ignore=E402,W503
    - id: check-ast
    - id: check-case-conflict
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
