version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.8
        environment:
          PRE_COMMIT_HOME: /home/circleci/cache/pre-commit
      - image: minio/minio:RELEASE.2022-07-04T21-02-54Z
        environment:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          MINIO_REGION: us-east-1
        entrypoint: sh
        command: ['-c', 'mkdir -p /data1 && mkdir -p /data2 && mkdir -p /data3 && mkdir -p /data4 && minio server /data{1...4}']
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-python-3.9.8-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/cache/pip
            - /home/circleci/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Install dependencies
          command: |
            pip install --cache-dir /home/circleci/cache/pip -r requirements_test.txt
            pre-commit install --install-hooks
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: v1-python-3.9.8-dependencies-{{ checksum "requirements_test.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/cache/pip
            - /home/circleci/cache/pre-commit
            - ./cc-test-reporter
      - run:
          name: Run linting
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            ./test_mbtiles_s3_server.sh
            coverage combine
            coverage xml
            ./cc-test-reporter after-build
